### ISSUE TITLE
Remove deprecated API

### ISSUE THREAD

**Issue by devunion** [Rob--W/browser-action-jplib#14]
Hi, could you update the library to avoid of using deprecated API?

There is stack from FF 31:

"DEPRECATED: The widget module is deprecated.  Please consider using the sdk/ui module instead.
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 113, in startup/<
    run(options);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 161, in run
    quit: exit
........................................................
  File "resource://jid1-bedgas3lmlydea-at-jetpack/browser-action/lib/browserAction.js", line 318, in Badge
    let tbw = createBadge(browserAction, badgeState);
  File "resource://jid1-bedgas3lmlydea-at-jetpack/browser-action/lib/browserAction.js", line 222, in createBadge
    onClick: function() {
  File "resource://jid1-bedgas3lmlydea-at-jetpack/toolbarwidget/lib/toolbarwidget.js", line 343, in exports.ToolbarWidget
    let sdkWidget = require('sdk/widget').Widget(options);

That will be really helpful. Thank you!

**Comment by Rob--W** [comment]
When I published this module, Firefox's support for Chrome-style buttons was bad. Now the situation has significantly been improved, so I recommend to use the built-in `sdk/ui` modules instead.

Firefox has started an initiative to bring the features of the Chrome extension API to Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1161828.
